#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
from datetime import datetime
from pathlib import Path


DEFAULT_SCHEMA_PATH = Path("schema_from_working_db.sql")
DEFAULT_OUT_PATH = Path("create_db_full.py")


def sanitize_schema_sql(sql: str) -> str:
    """
    Strip statements that reference sqlite_sequence (SQLite internal AUTOINCREMENT table).
    Some exports include:
      CREATE TABLE sqlite_sequence(name,seq);
      INSERT INTO sqlite_sequence VALUES(...);
    Those are not replayable and will error on executescript().
    """
    out_lines: list[str] = []
    skipping_stmt = False

    for line in sql.splitlines(True):
        if not skipping_stmt and re.search(r"\bsqlite_sequence\b", line, flags=re.IGNORECASE):
            # Drop this line; if statement continues, keep skipping until ';'
            if ";" not in line:
                skipping_stmt = True
            continue

        if skipping_stmt:
            if ";" in line:
                skipping_stmt = False
            continue

        out_lines.append(line)

    return "".join(out_lines)


def _strip_trailing_whitespace_preserve_newline(s: str) -> str:
    lines = s.splitlines()
    lines = [ln.rstrip() for ln in lines]
    return "\n".join(lines).rstrip() + "\n"


def render_create_db_full(schema_sql: str, schema_source: str) -> str:
    # Use triple single quotes so double quotes inside SQL don't need escaping.
    # Keep SQL as-is (post-sanitization) to preserve exact DDL/indexes.
    schema_sql = _strip_trailing_whitespace_preserve_newline(schema_sql)

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    return f"""#!/usr/bin/env python3
from __future__ import annotations

import argparse
import shutil
import sqlite3
from datetime import datetime
from pathlib import Path


# Auto-generated by tools/generate_create_db_full.py
# Source schema: {schema_source}
# Generated at: {generated_at}
#
# This script creates a fresh DB using the embedded schema below.
# NOTE: sqlite_sequence (SQLite internal AUTOINCREMENT table) is intentionally stripped.


SCHEMA_SQL = r'''{schema_sql}'''


def _backup_path_for(db_path: Path) -> Path:
    stamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
    return db_path.with_suffix(f".backup_{{stamp}}.db")


def create_db(db_path: Path, force: bool) -> None:
    db_path = db_path.resolve()
    db_path.parent.mkdir(parents=True, exist_ok=True)

    if db_path.exists():
        if not force:
            raise SystemExit(
                f"Refusing to overwrite existing DB at {{db_path}}.\\n"
                f"Re-run with --force to back up and recreate."
            )
        backup_path = _backup_path_for(db_path)
        shutil.copy2(db_path, backup_path)
        db_path.unlink()
        print(f"Backed up existing DB to: {{backup_path}}")

    conn = sqlite3.connect(str(db_path))
    try:
        conn.execute("PRAGMA foreign_keys = ON;")
        conn.executescript(SCHEMA_SQL)
        conn.execute("PRAGMA foreign_keys = ON;")
    finally:
        conn.close()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Create/recreate InventoryTrack SQLite database schema (embedded)."
    )
    parser.add_argument(
        "--db",
        default=str(Path(__file__).resolve().parent / "db" / "InventoryTrack.db"),
        help="Path to SQLite DB file (default: ./db/InventoryTrack.db)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Backup and overwrite DB if it already exists.",
    )
    args = parser.parse_args(argv)

    create_db(Path(args.db), force=bool(args.force))
    print(f"✅ DB created at: {{Path(args.db).resolve()}}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
"""


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="Generate create_db_full.py by embedding schema_from_working_db.sql."
    )
    p.add_argument(
        "--schema",
        default=str(DEFAULT_SCHEMA_PATH),
        help="Path to schema SQL file (default: ./schema_from_working_db.sql)",
    )
    p.add_argument(
        "--out",
        default=str(DEFAULT_OUT_PATH),
        help="Output path for create_db_full.py (default: ./create_db_full.py)",
    )
    p.add_argument(
        "--no-sanitize",
        action="store_true",
        help="Do not strip sqlite_sequence statements (NOT recommended).",
    )
    args = p.parse_args(argv)

    schema_path = Path(args.schema).resolve()
    out_path = Path(args.out).resolve()

    if not schema_path.exists():
        raise SystemExit(f"Schema file not found: {schema_path}")

    raw = schema_path.read_text(encoding="utf-8")
    if "CREATE TABLE" not in raw.upper():
        raise SystemExit(f"Schema file doesn't look like DDL: {schema_path}")

    sql = raw
    if not args.no_sanitize:
        sql = sanitize_schema_sql(sql)

    rendered = render_create_db_full(sql, str(schema_path))
    out_path.write_text(rendered, encoding="utf-8")

    # Make it obvious where it landed
    print(f"✅ Wrote: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

